export const corPrimaria = "#41d3be"
export const fundoClaro = "#f1f1f1"
export const conteudoClaro = "White"
export const textoFundoClaro = "grey"
export const fundoEscuro = "#363537"
export const textoFundoEscuro = "#FAFAFA"
export const conteudoEscuro = "“#5c5b5e"